set(SRC_FILES
    App.cpp
    TitleMenu.cpp
    StageIntroScreen.cpp
    StageData.cpp
    StageHud.cpp
    Map.cpp
    Brick.cpp
    Steel.cpp
    Grass.cpp
    Water.cpp
    Player.cpp
    ShieldEffect.cpp
    PowerUpItem.cpp
    Bullet.cpp
    Character.cpp
    Explosion.cpp
    Enemy.cpp
    RespawnEffect.cpp
    Base.cpp
    GameOverBanner.cpp
    StageClearScreen.cpp
)

set(INCLUDE_FILES
    App.hpp
    TitleMenu.hpp
    StageIntroScreen.hpp
    StageHud.hpp
    Player.hpp
    ShieldEffect.hpp
    PowerUpItem.hpp
    StageData.hpp
    Map.hpp
    TileHitInfo.hpp
    TileObject.hpp
    Brick.hpp
    Steel.hpp
    Grass.hpp
    Water.hpp
    Bullet.hpp
    Character.hpp
    Explosion.hpp
    Enemy.hpp
    RespawnEffect.hpp
    Base.hpp
    GameOverBanner.hpp
    StageClearScreen.hpp
    TextObject.hpp
)

set(TEST_FILES
)
